# Generated by Django 4.1.7 on 2023-03-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMenuItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text_content', models.TextField(max_length=4000)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_menu_child_items', to='tree_menu.treemenuitemmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TreeMenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('base_tree_menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_parent', to='tree_menu.treemenuitemmodel')),
            ],
        ),
    ]
